feat(contrib/fvuls) add function to acquire CPE information of network devices
wadda0714/vuls pull request #1
Opened 2023-07-21 02:14 UTC by wadda0714

If this Pull Request is work in progress, Add a prefix of “[WIP]” in the title.

# What did you implement:
These three subcommands

1. `future-vuls discover`
    Explore network devices within CIDR range.
2. `future-vuls add-server`
    Register specified network devices to Fvuls
3. `future-vuls add-cpe`
    Upload CPE information obtained by executing snmp2cpe on the specified network device to Fvuls

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:
You don't have to satisfy all of the following.

- [ ] Write tests
- [ ] Write documentation
- [ ] Check that there aren't other open pull requests for the same issue/feature
- [ ] Format your source code by `make fmt`
- [ ] Pass the test by `make test`
- [ ] Provide verification config / commands
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** YES

# Reference

* https://blog.github.com/2015-01-21-how-to-write-the-perfect-pull-request/

2023-07-24 09:05 UTC, sadayuki-matsuno requested changes
すでにmasterに取り込まれてる変更あるんですが、PRの出し方おかしいですね。
やりなおしてください

2023-07-24 09:05 UTC, sadayuki-matsuno commented on contrib/future-vuls/pkg/cpe/cpe.go
> +
無駄な空行をなくす（全部指摘しないですが、他にもあります）

2023-07-24 09:05 UTC, sadayuki-matsuno commented on contrib/future-vuls/pkg/cpe/cpe.go
> +					fmt.Printf("Done.\n")
ログ出力はvulsと同じloggerライブラリでしましょう

2023-07-24 09:05 UTC, sadayuki-matsuno commented on contrib/future-vuls/pkg/cpe/cpe.go
> +					ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
contextは1つの実行で1つだけでok

2023-07-24 09:05 UTC, sadayuki-matsuno commented on contrib/future-vuls/pkg/cpe/cpe.go
あと、実行した結果も書いてください

2023-07-24 09:23 UTC, wadda0714 commented on contrib/future-vuls/pkg/cpe/cpe.go
処理の概要は今書いてるものよりもっと細かい粒度のものということですか？

2023-07-24 09:28 UTC, wadda0714 commented on contrib/future-vuls/pkg/cpe/cpe.go
> +					fmt.Printf("Done.\n")
ログ出力に関しては、先に実装されていた`future-vuls upload`コマンドを参考にしていました(fmtをつかっていた)が、vulsに合わせる方がいいですか？

2023-07-26 04:53 UTC, wadda0714 commented on contrib/future-vuls/pkg/cpe/cpe.go
> +					result, err := exec.Command("./snmp2cpe", "v2c", addr, "public").CombinedOutput()
`snmp2cpe v2c 192.168.11.11 public | snmp2cpe convert | future-vuls add-cpe`みたいな感じですかね？
もしそうだとしたら1サーバごとにadd-cpeコマンドをユーザが打たないといけなくなりそうな気がします

2023-07-28 03:52 UTC, sadayuki-matsuno requested changes

2023-07-28 03:52 UTC, sadayuki-matsuno commented on contrib/future-vuls/pkg/cpe/cpe.go
> +					fmt.Printf("Done.\n")
future-vuls uploadがfmtなら一旦fmtでもいいですか。まぁOSSにPR出した時に指摘されたら直しましょう。

2023-07-28 03:52 UTC, sadayuki-matsuno commented on contrib/future-vuls/pkg/cpe/cpe.go
そうですね。話し合って決めた仕様の部分は少なくとも書きたいですね

2023-07-28 03:52 UTC, sadayuki-matsuno commented on contrib/future-vuls/pkg/server/server.go
> +		Run: func(_ *cobra.Command, args []string) {
runの部分までをmainに書いて、runの中身をここに書くと、このファイルとcobraの関係が疎結合になるし、ネストも深くならなくていいのでおすすめです

2023-07-28 03:52 UTC, sadayuki-matsuno commented on contrib/future-vuls/pkg/server/server.go
> +		Run: func(_ *cobra.Command, args []string) {
他のコマンドも同様です

2023-07-28 05:18 UTC, wadda0714 commented on contrib/future-vuls/pkg/server/server.go
> +		Run: func(_ *cobra.Command, args []string) {
変更しようと思ったのですが、懸念点が二つほどあります。

1. server.goなどの上の方で定義しているコマンドの引数の変数の定義をmain.goに移動させなければならないため、どのコマンドがどの引数を必要としているのかパッとみて分かりにくくなりそう
2. 単純にmain.goの文量が増えてしまい読みにくくなる

1に関してはserver.goと同じファイルの中でrunの中身の関数を別に分けて書くことで関数自体を疎結合にすることはできると思います。
現時点での実装はsnmp2cpeのコマンドの定義の仕方を参考にしています。
snmp2cpeの方ではrunの中身の関数の処理の肝心な部分をさらに別ファイルに分けたりしているようです(snmp2cpe convertであればコマンドの定義を行なっているファイルと実際にconvertする部分は別ファイル)

聞きたいこととしては、このまま松野さんの案で実装するか、それとも疎結合になってさえいれば他の方法でもいいのかということです。

2023-07-28 08:12 UTC, wadda0714 commented on contrib/future-vuls/pkg/server/server.go
> +		Run: func(_ *cobra.Command, args []string) {
回答済み

2023-08-01 02:32 UTC, wadda0714 commented on contrib/future-vuls/pkg/cpe/cpe.go
> +					result, err := exec.Command("./snmp2cpe", "v2c", addr, "public").CombinedOutput()
kanbeさん回答済み
今回は内部実行でいいとのこと

2023-08-02 03:55 UTC, sadayuki-matsuno requested changes

2023-08-02 03:55 UTC, sadayuki-matsuno commented on contrib/future-vuls/cmd/main.go
mainにはcobraの設定くらいを書いて、実際の処理は別ファイルにまとめたいですね
discoverみたいに

2023-08-03 01:32 UTC, sadayuki-matsuno requested changes

2023-08-03 01:32 UTC, sadayuki-matsuno commented on contrib/future-vuls/pkg/cpe/cpe.go
> +func AddCpeDataToFvuls(url string, token string, outputFile string) error {
errorが戻り値にあるfunctionの中身で、osExitするのはよくないので、エラーをちゃんと返して呼び出し元でハンドリングしましょう

2023-08-03 01:32 UTC, sadayuki-matsuno commented
あと、既存のコードも同じような構成に書き換えて欲しいです

2023-08-03 03:22 UTC, sadayuki-matsuno requested changes
コードレビューのやり取りが比較的多いので、毎回もう直すところがないか確認するようにお願いします。
あと実装中に不安になったところや疑問点は最初に全部洗い出してPR出す時に質問してください

2023-08-03 03:22 UTC, sadayuki-matsuno commented on contrib/future-vuls/pkg/cpe/cpe.go
> +		return -1, fmt.Errorf("Failed to create request. err: %v\n", err)
ここを-1にした理由はなんですか？

2023-08-03 03:22 UTC, sadayuki-matsuno commented on contrib/future-vuls/pkg/cpe/cpe.go
> +	fmt.Printf("Uploading CPE to %v...\n", fmt.Sprintf("%v/pkgCpe/cpe", url))
Sprintf１つでは表現できないですか？

2023-08-03 03:22 UTC, sadayuki-matsuno commented on contrib/future-vuls/pkg/cpe/cpe.go
> +				fmt.Printf("%v: Failed to Fetch serverID. err: %v\n", addr, err)
formatの方が事前にわかっている時は、%vを使わずに型指定しましょう

2023-08-03 03:22 UTC, sadayuki-matsuno commented on contrib/future-vuls/pkg/cpe/cpe.go
> +				} else {
ここはelseを使うのではなく、errが発生したらcontinueするようにしましょう

2023-08-03 03:27 UTC, wadda0714 commented on contrib/future-vuls/pkg/cpe/cpe.go
> +		return -1, fmt.Errorf("Failed to create request. err: %v\n", err)
普通のint型にnilがないのでserverIDが取りえない値に設定した感じです

2023-08-03 03:32 UTC, wadda0714 commented on contrib/future-vuls/pkg/cpe/cpe.go
> +	fmt.Printf("Uploading CPE to %v...\n", fmt.Sprintf("%v/pkgCpe/cpe", url))
これ以外だと/pkgCpe/cpe+urlと書くぐらいしか思いつきませんが、
あんまりgolangでは+を使わないと前に教えていただいたのでこの書き方にしてます

2023-08-03 07:07 UTC, sadayuki-matsuno requested changes

2023-08-03 07:07 UTC, sadayuki-matsuno commented on contrib/future-vuls/pkg/server/server.go
> +		if params.FvulsSync == true && params.UUID == "" {
booleanの判定で `== ture` と書くのは冗長です

2023-08-03 07:07 UTC, sadayuki-matsuno commented on contrib/future-vuls/pkg/server/server.go
> +			successFlag = true
これは何のためのflagですか？

2023-08-03 07:07 UTC, sadayuki-matsuno commented on contrib/future-vuls/cmd/main.go
> +			if err := upload.UploadToFvuls(serverUUID, groupID, url, token, tags, stdIn); err != nil {
stdInがなければerrにするのであれば、ここの段階でエラーにして処理を中止してください

2023-08-03 07:38 UTC, sadayuki-matsuno commented on contrib/future-vuls/cmd/main.go
> +	rootCmd.AddCommand(cmdFvulsUploader)
これ二つ登録されてませんか？

2023-08-04 04:50 UTC, merged